2 svd2pac doesnt find referenced cluster if derivedfrom point to an item of array cluster
Infineon/svd2pac pull request #13
Opened 2024-04-30 16:00 UTC by pellico

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

Description
By fixing this bug the code has been heavily restructured for easier support of _derived_from_ feature. _derived_from_ is supported also for registers. It has been enabled a feature in json in order to preserve the order of item tera template. Now the entity in generated code are in the same sequence as in xml.
No generated API.

Related Issue
#2

2024-05-02 06:31 UTC, manczak-ifx requested changes
Please refer to the github project https://github.com/Infineon/regmock-rs

2024-05-02 06:31 UTC, manczak-ifx commented on README.md
> +  An implementaion of that interface is provided by [`regmock-rs`](https://bitbucket.vih.infineon.com/projects/OXIDE/repos/regmock-rs/browse).
change link to the github repository

2024-05-02 06:31 UTC, manczak-ifx commented on README.md
> +e.g. unittesting see the documentation of [`regmock-rs`](https://bitbucket.vih.infineon.com/projects/OXIDE/repos/regmock-rs/browse).
change link to the github repository

2024-05-02 06:38 UTC, pellico commented on README.md
> +  An implementaion of that interface is provided by [`regmock-rs`](https://bitbucket.vih.infineon.com/projects/OXIDE/repos/regmock-rs/browse).
Fixed

2024-05-02 06:38 UTC, pellico commented on README.md
> +e.g. unittesting see the documentation of [`regmock-rs`](https://bitbucket.vih.infineon.com/projects/OXIDE/repos/regmock-rs/browse).
Fixed

2024-05-02 06:55 UTC, manczak-ifx approved these changes
Build #12. Approved from CSS DSI.

2024-05-06 09:07 UTC, andreasWallnerIFX approved these changes

2024-05-06 10:21 UTC, merged