Consistently use headerStructName for peripherals' module and structure identifiers
Infineon/svd2pac pull request #39
Opened 2024-08-29 17:05 UTC by jnkr-ifx

PR #37 uses the `headerStructName` field to define module and structure names. However, this change was not consistently applied throughout the generated code -- most references to peripherals use the peripheral name even if a header struct name is explicitly set. PSoC SVD files produce many compile errors when #37 is applied due to this inconsistency.

This commit changes all references to peripheral structures and modules to use the `module_id` and `struct_id` fields instead of inferring it from the peripheral names. Additionally, the peripheral `module_id` is now derived from the `headerStructName` for consistency with the logic in `push_current_item_svd_path`.

I encountered some issues with feature flags -- the existing logic in `Cargo_toml.tera` assumed that, in the case of a derived peripheral, the peripheral's feature flag would be the peripheral's name converted to a module identifier, and that the parent feature flag would be the peripheral's module identifier. However, in the case of peripheral derived from a struct with a `headerStructName`, this logic fails as the parent peripheral's name is not the same as its module identifier. I fixed this by changing the feature flag name to match the module name instead of the peripheral name. **This change means derived peripherals no longer have separate feature flags from their parents** -- if this is undesirable, an alternative would be to continue using the peripheral name for the feature flag, and add a field to the IR representation of a derived peripheral that allows us to keep track of the parent peripheral name when it's distinct from the module name.  

Lastly, this commit adds a test case of a simple peripheral with a `headerStructName`, which fails before this commit and passes after.

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md

2024-09-11 09:16 UTC, pellico submitted a review, later dismissed

2024-09-11 12:12 UTC, andreasWallnerIFX requested changes
Mostly just a few typos

2024-09-11 13:25 UTC, pellico commented on Cargo.toml
> +# it shall be not used
A mistake the feature will be removed, I forgotten to remove it.

2024-09-11 13:37 UTC, pellico approved these changes

2024-09-17 16:02 UTC, andreasWallnerIFX approved these changes

2024-09-17 16:26 UTC, merged